name: Ejecutar Terraform

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicializar Terraform
        working-directory: Terraform
        run: terraform init

      - name: Validar Terraform
        working-directory: Terraform
        run: terraform validate

      - name: Aplicar Terraform
        working-directory: Terraform
        env:
          TF_VAR_github_token: ${{ secrets.PAT_GASTON }}
          TF_VAR_github_owner: Gaston2018
        run: terraform apply -auto-approve
